<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>acadbot_slam</name>
  <version>1.0.0</version>
  <description>slam_toolbox configuration and launch files for AcadBot (LiDAR SLAM).</description>
  <maintainer email="wael.alsayegh@inmind.ai">Wael Al Sayegh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
